service: lambda-template

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    NODE_ENV: production

functions:
  hello:
    handler: src/handler.execute
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000