service: lambda-template

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  tracing:
    lambda: true
  environment:
    NODE_ENV: production
    POWERTOOLS_SERVICE_NAME: user-service
    POWERTOOLS_TRACER_CAPTURE_RESPONSE: true
    POWERTOOLS_TRACER_CAPTURE_ERROR: true
    LOG_LEVEL: INFO
    DB_USER: root
    DB_PASS: password
    DB_NAME: database
    DB_HOST: localhost


functions:
  hello:
    handler: src/handler.execute
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000